# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      TARGET_PLATFORM: linux/arm/v7


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Docker Login
      if: success()
      run: |
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
    - name: Detect Services
      if: success()
      run: |
        SERVICES_PATH=./services
        OUTPUT_PATH=$runner.temp

        echo "SERVICES_PATH="$SERVICES_PATH
        echo "OUTPUT_PATH="$OUTPUT_PATH
        echo ""

        if [ ! -d $SERVICES_PATH ]; then
          echo "services directory missing: "$SERVICES_PATH
          exit 1
        fi

        services_found=()
        for path in $SERVICES_PATH/*; do
          if [[ -d $path ]]; then
            SERVICE_NAME=$(basename $path)
            SVC_PATH=$SERVICES_PATH/$SERVICE_NAME

            echo "Checking $SVC_PATH"

            if [ ! -f $SVC_PATH/Dockerfile ]; then
              echo "service $SERVICE_NAME is missing its Dockerfile"
              echo "here's the contents of $SVC_PATH"
              ls -l $SVC_PATH
              exit 1
            fi

            echo "found service "$SERVICE_NAME
            services_found+=("$SERVICE_NAME")
          fi
        done

        if [ ${#services_found[@]} -eq 0 ]; then
          echo "no services found in ./services"
          exit 1
        else
          num_of_services_found="${#services_found[@]}"
          echo ""
          echo "found a total of "$num_of_services_found" services"
        fi

        for service_name in "${services_found[@]}"
        do
          echo $service_name
        done

        echo "::set-env name=services_found::$services_found"
    - name: Run Buildx (push image)
      if: success()
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        PROJECT_NAME=${GITHUB_REPOSITORY##*/}
        ACCOUNT_USERNAME=$(echo $GITHUB_REPOSITORY | cut -d/ -f1)

        echo "TARGET_PLATFORM="$TARGET_PLATFORM
        echo "IMAGE_NAME="$IMAGE_NAME
        echo "GITHUB_REF="$GITHUB_REF
        echo "BRANCH_NAME="$BRANCH_NAME
        echo "GITHUB_SHA="$GITHUB_SHA
        echo "GITHUB_REPOSITORY="$GITHUB_REPOSITORY
        echo "ACCOUNT_USERNAME="$ACCOUNT_USERNAME
        echo "PROJECT_NAME"=$PROJECT_NAME
        echo "services_found="$services_found

        # while read service_name; do
        #   IMAGE_NAME=$ACCOUNT_USERNAME'/'$PROJECT_NAME'_'$service_name
        #   SERVICE_PATH=services/$service_name
        #   echo '-----------------------------------------'
        #   echo 'Publishing image '$IMAGE_NAME' from path '$SERVICE_PATH
        #   echo '-----------------------------------------'
        #
        # done < $SERVICES_FOUND_FILE_PATH


        # cd services/light_sensor
        #
        # docker buildx build \
        #   --platform  $DOCKER_TARGET_PLATFORM \
        #   --tag $DOCKER_IMAGE \
        #   --file ./Dockerfile \
        #   --output type=image,push=true .
