# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: rromanotero/test_repo_light_sensor
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm/v7


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Docker Login
      if: success()
      run: |
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
    - name: Run Buildx (push image)
      if: success()
      run: |
        BRANCH_NAME=${GITHUB_HEAD_REF##*/}

        echo "DOCKER_TARGET_PLATFORM="$DOCKER_TARGET_PLATFORM
        echo "DOCKER_IMAGE="$DOCKER_IMAGE
        echo "GITHUB_HEAD_REF="$GITHUB_HEAD_REF
        echo "BRANCH_NAME="$BRANCH_NAME
        echo "GITHUB_SHA="$GITHUB_SHA


        cd services/light_sensor
        
        docker buildx build \
          --platform  $DOCKER_TARGET_PLATFORM \
          --tag $DOCKER_IMAGE \
          --file ./Dockerfile \
          --output type=image,push=true .
